using TTA.BusinessLogic.Features.GameEvents.Commands;

namespace TTA.BusinessLogic.Features.GameEvents.DTOs;

/// <summary>
/// Data transfer object for creating a new game event supplied by the client application.
/// </summary>
/// <param name="Id">The unique identifier generated by the client.</param>
/// <param name="MatchLineupId">The match lineup identifier.</param>
/// <param name="EventDefinitionId">The event definition identifier.</param>
/// <param name="PeriodNumber">The period number when the event occurred.</param>
/// <param name="EventTimestamp">The client-side UTC timestamp when the event occurred.</param>
/// <param name="IsLeadToGoal">Indicates whether this event leads to a goal.</param>
public record CreateGameEventRequest(
    Guid Id,
    Guid MatchLineupId,
    Guid EventDefinitionId,
    int PeriodNumber,
    DateTime EventTimestamp,
    bool IsLeadToGoal);

/// <summary>
/// Mapping extensions for <see cref="CreateGameEventRequest"/>.
/// </summary>
public static class CreateGameEventRequestExtensions
{
    /// <summary>
    /// Maps a batch collection of request DTOs directly to a MediatR execution command.
    /// </summary>
    /// <param name="requests">Collection of request DTOs.</param>
    /// <param name="matchId">The match identifier from route context.</param>
    /// <returns>A configured <see cref="CreateGameEventsCommand"/>.</returns>
    public static CreateGameEventsCommand ToCommand(this IEnumerable<CreateGameEventRequest> requests, Guid matchId) => new(
        MatchId: matchId,
        Events: requests);
}