using MediatR;

namespace TTA.BusinessLogic.Features.PlayerPresences.Commands;

/// <summary>
/// Represents an individual player presence item containing client-generated ID and lineup reference.
/// </summary>
/// <param name="Id">The unique identifier generated by the client application.</param>
/// <param name="MatchLineupId">The unique identifier of the player's match lineup entry.</param>
public record PlayerPresenceItem(Guid Id, Guid MatchLineupId);

/// <summary>
/// Command to initialize player presence for an explicit list of players starting a specific match period.
/// </summary>
/// <param name="MatchId">The unique identifier value of the active match context.</param>
/// <param name="PeriodNumber">The relative match period sequence number being started.</param>
/// <param name="TimeIn">The client-generated UTC timestamp marking when players entered the field.</param>
/// <param name="PresenceItems">The distinct collection containing player presence items starting this period block.</param>
public record InitializePresenceCommand(
    Guid MatchId,
    int PeriodNumber,
    DateTime TimeIn,
    IEnumerable<PlayerPresenceItem> PresenceItems) : IRequest;