using MediatR;
using TTA.DataAccess.Enums;
using TTA.DataAccess.Models;

namespace TTA.BusinessLogic.Features.TimeAnchors.Commands;

/// <summary>
/// Command to create a new time anchor for a match timeline using client-generated parameters.
/// </summary>
/// <param name="Id">The unique identifier of the time anchor generated by the client.</param>
/// <param name="MatchId">The unique identifier of the match.</param>
/// <param name="PeriodNumber">The match period number (e.g., 1, 2, etc.).</param>
/// <param name="Type">The type of the time anchor (e.g., PeriodStart, PeriodEnd).</param>
/// <param name="Timestamp">The client-side UTC timestamp when the anchor occurred.</param>
public record CreateTimeAnchorCommand(
    Guid Id,
    Guid MatchId,
    int PeriodNumber,
    TimeAnchorType Type,
    DateTime Timestamp) : IRequest<Guid>;

/// <summary>
/// Extensions for mapping CreateTimeAnchorCommand to domain models.
/// </summary>
public static class CreateTimeAnchorCommandExtensions
{
    /// <summary>
    /// Maps the creation command to a TimeAnchor entity preserving client-supplied Id and Timestamp.
    /// </summary>
    /// <param name="cmd">The command instance.</param>
    /// <returns>A new TimeAnchor entity.</returns>
    public static TimeAnchor ToModel(this CreateTimeAnchorCommand cmd) => new()
    {
        Id = cmd.Id,
        MatchId = cmd.MatchId,
        PeriodNumber = cmd.PeriodNumber,
        Type = cmd.Type,
        Timestamp = cmd.Timestamp
    };
}