namespace TTA.BusinessLogic.Features.PlayerPresences.DTOs;

/// <summary>
/// Data transfer object for creating or updating a player presence interval supplied in batch synchronization.
/// </summary>
/// <param name="Id">The unique identifier generated by the client application.</param>
/// <param name="MatchLineupId">The unique identifier of the match lineup entry.</param>
/// <param name="PeriodNumber">The period number during which the presence interval occurred.</param>
/// <param name="TimeIn">The client-side UTC timestamp when the player entered the field.</param>
/// <param name="TimeOut">The client-side UTC timestamp when the player left the field (null if active at recording time).</param>
public record CreatePlayerPresenceRequest(
    Guid Id,
    Guid MatchLineupId,
    int PeriodNumber,
    DateTime TimeIn,
    DateTime? TimeOut);