using TTA.BusinessLogic.Features.TimeAnchors.Commands;
using TTA.DataAccess.Enums;

namespace TTA.BusinessLogic.Features.TimeAnchors.DTOs;

/// <summary>
/// Data transfer object for creating a new time anchor provided by the client application.
/// </summary>
/// <param name="Id">The unique identifier of the time anchor generated by the client.</param>
/// <param name="PeriodNumber">The match period number (e.g., 1, 2, etc.).</param>
/// <param name="Type">The type of the time anchor (e.g., PeriodStart, PeriodEnd).</param>
/// <param name="Timestamp">The client-side UTC timestamp when the anchor occurred.</param>
public record CreateTimeAnchorRequest(
    Guid Id,
    int PeriodNumber,
    TimeAnchorType Type,
    DateTime Timestamp);

/// <summary>
/// Mapping extensions for <see cref="CreateTimeAnchorRequest"/>.
/// </summary>
public static class CreateTimeAnchorRequestExtensions
{
    /// <summary>
    /// Maps a batch collection of request DTOs directly to a MediatR execution command.
    /// </summary>
    /// <param name="requests">Collection of request DTOs.</param>
    /// <param name="matchId">The match identifier from route context.</param>
    /// <returns>A configured <see cref="CreateTimeAnchorsCommand"/>.</returns>
    public static CreateTimeAnchorsCommand ToCommand(this IEnumerable<CreateTimeAnchorRequest> requests, Guid matchId) => new(
        MatchId: matchId,
        Anchors: requests);
}